--
-- PostgreSQL database dump
--

-- Dumped from database version 9.4.5
-- Dumped by pg_dump version 9.4.5
-- Started on 2016-02-11 00:21:12 COT

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

--
-- TOC entry 216 (class 3079 OID 11935)
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- TOC entry 2367 (class 0 OID 0)
-- Dependencies: 216
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET search_path = public, pg_catalog;

--
-- TOC entry 229 (class 1255 OID 23759)
-- Name: fn_crearusuarioinstalacion(character varying, character varying, character varying, character varying, character varying, boolean, date); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION fn_crearusuarioinstalacion(character varying, character varying, character varying, character varying, character varying, boolean, date) RETURNS character varying
    LANGUAGE plpgsql
    AS $_$ 

DECLARE 
usuario_login ALIAS FOR $1;
usuario_password ALIAS FOR $2;
usuario_nombre ALIAS FOR $3;
usuario_apellido ALIAS FOR $4;
usuario_correo ALIAS FOR $5;
usuario_genero ALIAS FOR $6;
usuario_fechanacimiento ALIAS FOR $7;
BEGIN 

INSERT INTO credencial(
            id, nombre, created_at, updated_at, deleted_at)
    VALUES (default, 'admin', default, default, null);

INSERT INTO localidad(
            id, created_at, updated_at, deleted_at, nombre, localidad_id)
    VALUES (default, default, default, null, 'Localidad de prueba', null);

INSERT INTO tipo_documento(
            id, created_at, updated_at, deleted_at, nombre)
    VALUES (default, default, default, null, 'Tipo documento de prueba');

INSERT INTO usuario(
            id, user_name, password, actived, last_login_at, created_at, 
            updated_at, deleted_at)
    VALUES (default, usuario_login, usuario_password, default, null, default, 
            default, null);

INSERT INTO dato_usuario(
            id, created_at, updated_at, deleted_at, usuario_id, nombre, apellido, 
            correo, genero, fecha_nacimiento, localidad_id, tipo_documento_id, 
            organizacion_id)
    VALUES (default, default, default, null, currval('usuario_id_seq'::regclass), usuario_nombre, usuario_apellido, 
            usuario_correo, usuario_genero, usuario_fechanacimiento, currval('localidad_id_seq'::regclass), 
            currval('tipo_documento_id_seq'::regclass), null);

INSERT INTO usuario_credencial(
            id, usuario_id, credencial_id, created_at)
    VALUES (default, currval('usuario_id_seq'::regclass), currval('credencial_id_seq'::regclass), default);
    
RETURN 'OK'; 
END; 
$_$;


ALTER FUNCTION public.fn_crearusuarioinstalacion(character varying, character varying, character varying, character varying, character varying, boolean, date) OWNER TO postgres;

--
-- TOC entry 172 (class 1259 OID 17844)
-- Name: bitacora_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE bitacora_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE bitacora_id_seq OWNER TO postgres;

--
-- TOC entry 2368 (class 0 OID 0)
-- Dependencies: 172
-- Name: SEQUENCE bitacora_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE bitacora_id_seq IS 'DbWrench Autogenerated Sequence.';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 173 (class 1259 OID 17846)
-- Name: bitacora; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE bitacora (
    id bigint DEFAULT nextval('bitacora_id_seq'::regclass) NOT NULL,
    usuario_id bigint NOT NULL,
    accion character varying(80) NOT NULL,
    tabla character varying(80) NOT NULL,
    registro bigint,
    observacion character varying(1024),
    fecha timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE bitacora OWNER TO postgres;

--
-- TOC entry 174 (class 1259 OID 17854)
-- Name: categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE categoria_id_seq OWNER TO postgres;

--
-- TOC entry 2369 (class 0 OID 0)
-- Dependencies: 174
-- Name: SEQUENCE categoria_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE categoria_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 175 (class 1259 OID 17856)
-- Name: categoria; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE categoria (
    id bigint DEFAULT nextval('categoria_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(45) NOT NULL
);


ALTER TABLE categoria OWNER TO postgres;

--
-- TOC entry 176 (class 1259 OID 17862)
-- Name: credencial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE credencial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE credencial_id_seq OWNER TO postgres;

--
-- TOC entry 2370 (class 0 OID 0)
-- Dependencies: 176
-- Name: SEQUENCE credencial_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE credencial_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 177 (class 1259 OID 17864)
-- Name: credencial; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE credencial (
    id bigint DEFAULT nextval('credencial_id_seq'::regclass) NOT NULL,
    nombre character varying(80) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


ALTER TABLE credencial OWNER TO postgres;

--
-- TOC entry 178 (class 1259 OID 17870)
-- Name: dato_usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE dato_usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE dato_usuario_id_seq OWNER TO postgres;

--
-- TOC entry 2371 (class 0 OID 0)
-- Dependencies: 178
-- Name: SEQUENCE dato_usuario_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE dato_usuario_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 179 (class 1259 OID 17872)
-- Name: dato_usuario; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE dato_usuario (
    id bigint DEFAULT nextval('dato_usuario_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    usuario_id bigint NOT NULL,
    nombre character varying(45) NOT NULL,
    apellido character varying(45) NOT NULL,
    correo character varying(70) NOT NULL,
    genero boolean NOT NULL,
    fecha_nacimiento date NOT NULL,
    localidad_id bigint NOT NULL,
    tipo_documento_id bigint NOT NULL,
    organizacion_id bigint
);


ALTER TABLE dato_usuario OWNER TO postgres;

--
-- TOC entry 2372 (class 0 OID 0)
-- Dependencies: 179
-- Name: COLUMN dato_usuario.genero; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN dato_usuario.genero IS 'true = femenino | false = masculino';


--
-- TOC entry 180 (class 1259 OID 17878)
-- Name: detalle_pqrs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE detalle_pqrs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE detalle_pqrs_id_seq OWNER TO postgres;

--
-- TOC entry 2373 (class 0 OID 0)
-- Dependencies: 180
-- Name: SEQUENCE detalle_pqrs_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE detalle_pqrs_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 181 (class 1259 OID 17880)
-- Name: detalle_pqrs; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE detalle_pqrs (
    id bigint DEFAULT nextval('detalle_pqrs_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    pqrs_id bigint NOT NULL,
    respuesta character varying(2048) NOT NULL,
    usuario_id bigint NOT NULL
);


ALTER TABLE detalle_pqrs OWNER TO postgres;

--
-- TOC entry 182 (class 1259 OID 17889)
-- Name: estado_pqrs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE estado_pqrs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE estado_pqrs_id_seq OWNER TO postgres;

--
-- TOC entry 2374 (class 0 OID 0)
-- Dependencies: 182
-- Name: SEQUENCE estado_pqrs_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE estado_pqrs_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 183 (class 1259 OID 17891)
-- Name: estado_pqrs; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE estado_pqrs (
    id bigint DEFAULT nextval('estado_pqrs_id_seq'::regclass) NOT NULL,
    nombre character varying(50) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


ALTER TABLE estado_pqrs OWNER TO postgres;

--
-- TOC entry 2375 (class 0 OID 0)
-- Dependencies: 183
-- Name: COLUMN estado_pqrs.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN estado_pqrs.actived IS 'TRUE activado ; FALSE desactivado';


--
-- TOC entry 184 (class 1259 OID 17898)
-- Name: evento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE evento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE evento_id_seq OWNER TO postgres;

--
-- TOC entry 2376 (class 0 OID 0)
-- Dependencies: 184
-- Name: SEQUENCE evento_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE evento_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 185 (class 1259 OID 17900)
-- Name: evento; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE evento (
    id bigint DEFAULT nextval('evento_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    imagen character varying(37),
    nombre character varying(45) NOT NULL,
    descripcion character varying(1024) NOT NULL,
    fecha_inicial_evento timestamp without time zone NOT NULL,
    fecha_final_evento timestamp without time zone NOT NULL,
    lugar_latitud character varying(100) NOT NULL,
    lugar_longitud character varying(100) NOT NULL,
    direccion character varying(150) NOT NULL,
    costo integer DEFAULT 0,
    usuario_id bigint NOT NULL,
    categoria_id bigint,
    fecha_inicial_publicacion timestamp without time zone NOT NULL,
    fecha_final_publicacion timestamp without time zone NOT NULL
);


ALTER TABLE evento OWNER TO postgres;

--
-- TOC entry 186 (class 1259 OID 17910)
-- Name: evento_patrocinador_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE evento_patrocinador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE evento_patrocinador_id_seq OWNER TO postgres;

--
-- TOC entry 2377 (class 0 OID 0)
-- Dependencies: 186
-- Name: SEQUENCE evento_patrocinador_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE evento_patrocinador_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 187 (class 1259 OID 17912)
-- Name: evento_patrocinador; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE evento_patrocinador (
    id bigint DEFAULT nextval('evento_patrocinador_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    evento_id bigint NOT NULL,
    patrocinador_id bigint NOT NULL
);


ALTER TABLE evento_patrocinador OWNER TO postgres;

--
-- TOC entry 188 (class 1259 OID 17918)
-- Name: localidad_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE localidad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE localidad_id_seq OWNER TO postgres;

--
-- TOC entry 2378 (class 0 OID 0)
-- Dependencies: 188
-- Name: SEQUENCE localidad_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE localidad_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 189 (class 1259 OID 17920)
-- Name: localidad; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE localidad (
    id bigint DEFAULT nextval('localidad_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(45) NOT NULL,
    localidad_id bigint
);


ALTER TABLE localidad OWNER TO postgres;

--
-- TOC entry 190 (class 1259 OID 17926)
-- Name: organizacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE organizacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE organizacion_id_seq OWNER TO postgres;

--
-- TOC entry 2379 (class 0 OID 0)
-- Dependencies: 190
-- Name: SEQUENCE organizacion_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE organizacion_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 191 (class 1259 OID 17928)
-- Name: organizacion; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE organizacion (
    id bigint DEFAULT nextval('organizacion_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(45) NOT NULL,
    direccion character varying(200) NOT NULL,
    telefono character varying(45) NOT NULL,
    fax character varying(45),
    correo character varying(100) NOT NULL,
    pagina_web character varying(100)
);


ALTER TABLE organizacion OWNER TO postgres;

--
-- TOC entry 192 (class 1259 OID 17937)
-- Name: patrocinador_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE patrocinador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE patrocinador_id_seq OWNER TO postgres;

--
-- TOC entry 2380 (class 0 OID 0)
-- Dependencies: 192
-- Name: SEQUENCE patrocinador_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE patrocinador_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 193 (class 1259 OID 17939)
-- Name: patrocinador; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE patrocinador (
    id bigint DEFAULT nextval('patrocinador_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(45) NOT NULL,
    telefono character varying(10),
    correo character varying(150) NOT NULL,
    direccion character varying(150)
);


ALTER TABLE patrocinador OWNER TO postgres;

--
-- TOC entry 194 (class 1259 OID 17945)
-- Name: pqrs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE pqrs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE pqrs_id_seq OWNER TO postgres;

--
-- TOC entry 2381 (class 0 OID 0)
-- Dependencies: 194
-- Name: SEQUENCE pqrs_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE pqrs_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 195 (class 1259 OID 17947)
-- Name: pqrs; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE pqrs (
    id bigint DEFAULT nextval('pqrs_id_seq'::regclass) NOT NULL,
    tipo_pqrs_id bigint NOT NULL,
    estado_pqrs_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    titulo character varying(50) NOT NULL,
    contenido character varying(2048) NOT NULL,
    usuario_id bigint NOT NULL
);


ALTER TABLE pqrs OWNER TO postgres;

--
-- TOC entry 196 (class 1259 OID 17956)
-- Name: recaudo_economico_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE recaudo_economico_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE recaudo_economico_id_seq OWNER TO postgres;

--
-- TOC entry 2382 (class 0 OID 0)
-- Dependencies: 196
-- Name: SEQUENCE recaudo_economico_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE recaudo_economico_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 197 (class 1259 OID 17958)
-- Name: recaudo_economico; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE recaudo_economico (
    id bigint DEFAULT nextval('recaudo_economico_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    evento_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    observacion character varying(1024),
    tarifa_id bigint NOT NULL,
    valor_total bigint DEFAULT 0 NOT NULL,
    valor_parcial bigint DEFAULT 0 NOT NULL
);


ALTER TABLE recaudo_economico OWNER TO postgres;

--
-- TOC entry 198 (class 1259 OID 17969)
-- Name: recordar_me_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE recordar_me_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE recordar_me_id_seq OWNER TO postgres;

--
-- TOC entry 2383 (class 0 OID 0)
-- Dependencies: 198
-- Name: SEQUENCE recordar_me_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE recordar_me_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 199 (class 1259 OID 17971)
-- Name: recordar_me; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE recordar_me (
    id bigint DEFAULT nextval('recordar_me_id_seq'::regclass) NOT NULL,
    usuario_id bigint NOT NULL,
    ip_address character varying(50) NOT NULL,
    hash_cookie character varying(32) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE recordar_me OWNER TO postgres;

--
-- TOC entry 200 (class 1259 OID 17976)
-- Name: rol_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE rol_id_seq OWNER TO postgres;

--
-- TOC entry 2384 (class 0 OID 0)
-- Dependencies: 200
-- Name: SEQUENCE rol_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE rol_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 201 (class 1259 OID 17978)
-- Name: tarifa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE tarifa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE tarifa_id_seq OWNER TO postgres;

--
-- TOC entry 2385 (class 0 OID 0)
-- Dependencies: 201
-- Name: SEQUENCE tarifa_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE tarifa_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 202 (class 1259 OID 17980)
-- Name: tarifa; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tarifa (
    id bigint DEFAULT nextval('tarifa_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    descripcion character varying(1024) NOT NULL,
    valor bigint NOT NULL,
    actived boolean DEFAULT true NOT NULL
);


ALTER TABLE tarifa OWNER TO postgres;

--
-- TOC entry 2386 (class 0 OID 0)
-- Dependencies: 202
-- Name: COLUMN tarifa.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN tarifa.actived IS 'TRUE activado ; FALSE desactivado';


--
-- TOC entry 203 (class 1259 OID 17990)
-- Name: tb_perrito; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tb_perrito (
    id integer NOT NULL,
    nombre character varying(50)
);


ALTER TABLE tb_perrito OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 17993)
-- Name: tb_perrito_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE tb_perrito_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE tb_perrito_id_seq OWNER TO postgres;

--
-- TOC entry 2387 (class 0 OID 0)
-- Dependencies: 204
-- Name: tb_perrito_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE tb_perrito_id_seq OWNED BY tb_perrito.id;


--
-- TOC entry 205 (class 1259 OID 17995)
-- Name: tipo_documento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE tipo_documento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE tipo_documento_id_seq OWNER TO postgres;

--
-- TOC entry 2388 (class 0 OID 0)
-- Dependencies: 205
-- Name: SEQUENCE tipo_documento_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE tipo_documento_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 206 (class 1259 OID 17997)
-- Name: tipo_documento; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tipo_documento (
    id bigint DEFAULT nextval('tipo_documento_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(45) NOT NULL
);


ALTER TABLE tipo_documento OWNER TO postgres;

--
-- TOC entry 207 (class 1259 OID 18003)
-- Name: tipo_pqrs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE tipo_pqrs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE tipo_pqrs_id_seq OWNER TO postgres;

--
-- TOC entry 2389 (class 0 OID 0)
-- Dependencies: 207
-- Name: SEQUENCE tipo_pqrs_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE tipo_pqrs_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 208 (class 1259 OID 18005)
-- Name: tipo_pqrs; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tipo_pqrs (
    id bigint DEFAULT nextval('tipo_pqrs_id_seq'::regclass) NOT NULL,
    nombre character varying(50) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


ALTER TABLE tipo_pqrs OWNER TO postgres;

--
-- TOC entry 2390 (class 0 OID 0)
-- Dependencies: 208
-- Name: COLUMN tipo_pqrs.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN tipo_pqrs.actived IS 'TRUE activado ; FALSE desactivado';


--
-- TOC entry 209 (class 1259 OID 18012)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE usuario_id_seq OWNER TO postgres;

--
-- TOC entry 2391 (class 0 OID 0)
-- Dependencies: 209
-- Name: SEQUENCE usuario_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 210 (class 1259 OID 18014)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE usuario (
    id bigint DEFAULT nextval('usuario_id_seq'::regclass) NOT NULL,
    user_name character varying(80) NOT NULL,
    password character varying(32) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    last_login_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


ALTER TABLE usuario OWNER TO postgres;

--
-- TOC entry 2392 (class 0 OID 0)
-- Dependencies: 210
-- Name: COLUMN usuario.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN usuario.actived IS 'TRUE = activado | FALSE = desactivado';


--
-- TOC entry 211 (class 1259 OID 18021)
-- Name: usuario_credencial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_credencial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE usuario_credencial_id_seq OWNER TO postgres;

--
-- TOC entry 2393 (class 0 OID 0)
-- Dependencies: 211
-- Name: SEQUENCE usuario_credencial_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_credencial_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 212 (class 1259 OID 18023)
-- Name: usuario_credencial; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE usuario_credencial (
    id bigint DEFAULT nextval('usuario_credencial_id_seq'::regclass) NOT NULL,
    usuario_id bigint NOT NULL,
    credencial_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE usuario_credencial OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 18028)
-- Name: usuario_gusta_categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_gusta_categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE usuario_gusta_categoria_id_seq OWNER TO postgres;

--
-- TOC entry 2394 (class 0 OID 0)
-- Dependencies: 213
-- Name: SEQUENCE usuario_gusta_categoria_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_gusta_categoria_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 214 (class 1259 OID 18030)
-- Name: usuario_gusta_categoria; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE usuario_gusta_categoria (
    id bigint DEFAULT nextval('usuario_gusta_categoria_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    usuario_id bigint NOT NULL,
    categoria_id bigint NOT NULL
);


ALTER TABLE usuario_gusta_categoria OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 18036)
-- Name: usuario_rol_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE usuario_rol_id_seq OWNER TO postgres;

--
-- TOC entry 2395 (class 0 OID 0)
-- Dependencies: 215
-- Name: SEQUENCE usuario_rol_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_rol_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 2139 (class 2604 OID 18038)
-- Name: id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY tb_perrito ALTER COLUMN id SET DEFAULT nextval('tb_perrito_id_seq'::regclass);


--
-- TOC entry 2159 (class 2606 OID 18040)
-- Name: pkbitacora; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY bitacora
    ADD CONSTRAINT pkbitacora PRIMARY KEY (id);


--
-- TOC entry 2161 (class 2606 OID 18042)
-- Name: pkcategoria; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY categoria
    ADD CONSTRAINT pkcategoria PRIMARY KEY (id);


--
-- TOC entry 2163 (class 2606 OID 18044)
-- Name: pkcredencial; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY credencial
    ADD CONSTRAINT pkcredencial PRIMARY KEY (id);


--
-- TOC entry 2169 (class 2606 OID 18046)
-- Name: pkdato_usuario; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY dato_usuario
    ADD CONSTRAINT pkdato_usuario PRIMARY KEY (id);


--
-- TOC entry 2173 (class 2606 OID 18048)
-- Name: pkdetalle_pqrs; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY detalle_pqrs
    ADD CONSTRAINT pkdetalle_pqrs PRIMARY KEY (id);


--
-- TOC entry 2175 (class 2606 OID 18050)
-- Name: pkestado_pqrs; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY estado_pqrs
    ADD CONSTRAINT pkestado_pqrs PRIMARY KEY (id);


--
-- TOC entry 2179 (class 2606 OID 18052)
-- Name: pkevento; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY evento
    ADD CONSTRAINT pkevento PRIMARY KEY (id);


--
-- TOC entry 2184 (class 2606 OID 18054)
-- Name: pkevento_patrocinador; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY evento_patrocinador
    ADD CONSTRAINT pkevento_patrocinador PRIMARY KEY (id);


--
-- TOC entry 2187 (class 2606 OID 18056)
-- Name: pklocalidad; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY localidad
    ADD CONSTRAINT pklocalidad PRIMARY KEY (id);


--
-- TOC entry 2189 (class 2606 OID 18058)
-- Name: pkorganizacion; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY organizacion
    ADD CONSTRAINT pkorganizacion PRIMARY KEY (id);


--
-- TOC entry 2191 (class 2606 OID 18060)
-- Name: pkpatrocinador; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY patrocinador
    ADD CONSTRAINT pkpatrocinador PRIMARY KEY (id);


--
-- TOC entry 2193 (class 2606 OID 18062)
-- Name: pkpqrs; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY pqrs
    ADD CONSTRAINT pkpqrs PRIMARY KEY (id);


--
-- TOC entry 2197 (class 2606 OID 18064)
-- Name: pkrecaudo_economico; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY recaudo_economico
    ADD CONSTRAINT pkrecaudo_economico PRIMARY KEY (id);


--
-- TOC entry 2202 (class 2606 OID 18066)
-- Name: pkrecordar_me; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY recordar_me
    ADD CONSTRAINT pkrecordar_me PRIMARY KEY (id);


--
-- TOC entry 2206 (class 2606 OID 18068)
-- Name: pktarifa; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tarifa
    ADD CONSTRAINT pktarifa PRIMARY KEY (id);


--
-- TOC entry 2208 (class 2606 OID 18070)
-- Name: pktipo_documento; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tipo_documento
    ADD CONSTRAINT pktipo_documento PRIMARY KEY (id);


--
-- TOC entry 2210 (class 2606 OID 18072)
-- Name: pktipo_pqrs; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tipo_pqrs
    ADD CONSTRAINT pktipo_pqrs PRIMARY KEY (id);


--
-- TOC entry 2212 (class 2606 OID 18074)
-- Name: pkusuario; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY usuario
    ADD CONSTRAINT pkusuario PRIMARY KEY (id);


--
-- TOC entry 2218 (class 2606 OID 18076)
-- Name: pkusuario_credencial; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT pkusuario_credencial PRIMARY KEY (id);


--
-- TOC entry 2223 (class 2606 OID 18078)
-- Name: pkusuario_gusta_categoria; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY usuario_gusta_categoria
    ADD CONSTRAINT pkusuario_gusta_categoria PRIMARY KEY (id);


--
-- TOC entry 2156 (class 1259 OID 18079)
-- Name: bitacora_fecha_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "bitacora_fecha_Idx" ON bitacora USING btree (fecha);


--
-- TOC entry 2157 (class 1259 OID 18080)
-- Name: bitacora_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "bitacora_usuario_id_Idx" ON bitacora USING btree (usuario_id);


--
-- TOC entry 2164 (class 1259 OID 18081)
-- Name: dato_usuario_localidad_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "dato_usuario_localidad_id_Idx" ON dato_usuario USING btree (localidad_id);


--
-- TOC entry 2165 (class 1259 OID 18082)
-- Name: dato_usuario_organizacion_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "dato_usuario_organizacion_id_Idx" ON dato_usuario USING btree (organizacion_id);


--
-- TOC entry 2166 (class 1259 OID 18083)
-- Name: dato_usuario_tipo_documento_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "dato_usuario_tipo_documento_id_Idx" ON dato_usuario USING btree (tipo_documento_id);


--
-- TOC entry 2167 (class 1259 OID 18084)
-- Name: dato_usuario_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "dato_usuario_usuario_id_Idx" ON dato_usuario USING btree (usuario_id);


--
-- TOC entry 2170 (class 1259 OID 18085)
-- Name: detalle_pqrs_pqrs_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "detalle_pqrs_pqrs_id_Idx" ON detalle_pqrs USING btree (pqrs_id);


--
-- TOC entry 2171 (class 1259 OID 18086)
-- Name: detalle_pqrs_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "detalle_pqrs_usuario_id_Idx" ON detalle_pqrs USING btree (usuario_id);


--
-- TOC entry 2176 (class 1259 OID 18087)
-- Name: evento_categoria_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "evento_categoria_id_Idx" ON evento USING btree (categoria_id);


--
-- TOC entry 2180 (class 1259 OID 18088)
-- Name: evento_patrocinador_evento_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "evento_patrocinador_evento_id_Idx" ON evento_patrocinador USING btree (evento_id);


--
-- TOC entry 2181 (class 1259 OID 18089)
-- Name: evento_patrocinador_evento_id_patrocinador_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "evento_patrocinador_evento_id_patrocinador_id_Idx" ON evento_patrocinador USING btree (evento_id, patrocinador_id);


--
-- TOC entry 2182 (class 1259 OID 18090)
-- Name: evento_patrocinador_patrocinador_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "evento_patrocinador_patrocinador_id_Idx" ON evento_patrocinador USING btree (patrocinador_id);


--
-- TOC entry 2177 (class 1259 OID 18091)
-- Name: evento_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "evento_usuario_id_Idx" ON evento USING btree (usuario_id);


--
-- TOC entry 2185 (class 1259 OID 18092)
-- Name: localidad_localidad_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "localidad_localidad_id_Idx" ON localidad USING btree (localidad_id);


--
-- TOC entry 2194 (class 1259 OID 18093)
-- Name: pqrs_tipo_pqrs_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "pqrs_tipo_pqrs_id_Idx" ON pqrs USING btree (tipo_pqrs_id);


--
-- TOC entry 2195 (class 1259 OID 18094)
-- Name: pqrs_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "pqrs_usuario_id_Idx" ON pqrs USING btree (usuario_id);


--
-- TOC entry 2198 (class 1259 OID 18095)
-- Name: recaudo_economico_evento_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "recaudo_economico_evento_id_Idx" ON recaudo_economico USING btree (evento_id);


--
-- TOC entry 2199 (class 1259 OID 18096)
-- Name: recaudo_economico_tarifa_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "recaudo_economico_tarifa_id_Idx" ON recaudo_economico USING btree (tarifa_id);


--
-- TOC entry 2200 (class 1259 OID 18097)
-- Name: recaudo_economico_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "recaudo_economico_usuario_id_Idx" ON recaudo_economico USING btree (usuario_id);


--
-- TOC entry 2203 (class 1259 OID 18098)
-- Name: recordar_me_ip_address_hash_cookie_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "recordar_me_ip_address_hash_cookie_Idx" ON recordar_me USING btree (ip_address, hash_cookie);


--
-- TOC entry 2204 (class 1259 OID 18099)
-- Name: recordar_me_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "recordar_me_usuario_id_Idx" ON recordar_me USING btree (usuario_id);


--
-- TOC entry 2213 (class 1259 OID 18100)
-- Name: usuario_actived_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_actived_Idx" ON usuario USING btree (actived);


--
-- TOC entry 2219 (class 1259 OID 18101)
-- Name: usuario_credencial_credencial_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_credencial_credencial_id_Idx" ON usuario_credencial USING btree (credencial_id);


--
-- TOC entry 2220 (class 1259 OID 18102)
-- Name: usuario_credencial_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_credencial_usuario_id_Idx" ON usuario_credencial USING btree (usuario_id);


--
-- TOC entry 2221 (class 1259 OID 18103)
-- Name: usuario_credencial_usuario_id_credencial_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "usuario_credencial_usuario_id_credencial_id_Idx" ON usuario_credencial USING btree (usuario_id, credencial_id);


--
-- TOC entry 2214 (class 1259 OID 18104)
-- Name: usuario_deleted_at_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_deleted_at_Idx" ON usuario USING btree (deleted_at);


--
-- TOC entry 2224 (class 1259 OID 18105)
-- Name: usuario_gusta_categoria_categoria_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_gusta_categoria_categoria_id_Idx" ON usuario_gusta_categoria USING btree (categoria_id);


--
-- TOC entry 2225 (class 1259 OID 18106)
-- Name: usuario_gusta_categoria_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_gusta_categoria_usuario_id_Idx" ON usuario_gusta_categoria USING btree (usuario_id);


--
-- TOC entry 2226 (class 1259 OID 18107)
-- Name: usuario_gusta_categoria_usuario_id_categoria_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "usuario_gusta_categoria_usuario_id_categoria_id_Idx" ON usuario_gusta_categoria USING btree (usuario_id, categoria_id);


--
-- TOC entry 2215 (class 1259 OID 18108)
-- Name: usuario_user_name_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "usuario_user_name_Idx" ON usuario USING btree (user_name);


--
-- TOC entry 2216 (class 1259 OID 18109)
-- Name: usuario_user_name_password_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_user_name_password_Idx" ON usuario USING btree (user_name, password);


--
-- TOC entry 2227 (class 2606 OID 18110)
-- Name: fk_bitacora_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY bitacora
    ADD CONSTRAINT fk_bitacora_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2228 (class 2606 OID 18115)
-- Name: fk_dato_usuario_localidad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY dato_usuario
    ADD CONSTRAINT fk_dato_usuario_localidad FOREIGN KEY (localidad_id) REFERENCES localidad(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2229 (class 2606 OID 18120)
-- Name: fk_dato_usuario_organizacion; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY dato_usuario
    ADD CONSTRAINT fk_dato_usuario_organizacion FOREIGN KEY (organizacion_id) REFERENCES organizacion(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2230 (class 2606 OID 18125)
-- Name: fk_dato_usuario_tipo_documento; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY dato_usuario
    ADD CONSTRAINT fk_dato_usuario_tipo_documento FOREIGN KEY (tipo_documento_id) REFERENCES tipo_documento(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2231 (class 2606 OID 18130)
-- Name: fk_dato_usuario_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY dato_usuario
    ADD CONSTRAINT fk_dato_usuario_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2232 (class 2606 OID 18135)
-- Name: fk_detalle_pqrs_pqrs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_pqrs
    ADD CONSTRAINT fk_detalle_pqrs_pqrs FOREIGN KEY (pqrs_id) REFERENCES pqrs(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2233 (class 2606 OID 18140)
-- Name: fk_detalle_pqrs_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_pqrs
    ADD CONSTRAINT fk_detalle_pqrs_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2234 (class 2606 OID 18145)
-- Name: fk_evento_categoria; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY evento
    ADD CONSTRAINT fk_evento_categoria FOREIGN KEY (categoria_id) REFERENCES categoria(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2236 (class 2606 OID 18150)
-- Name: fk_evento_patrocinador_evento; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY evento_patrocinador
    ADD CONSTRAINT fk_evento_patrocinador_evento FOREIGN KEY (evento_id) REFERENCES evento(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2237 (class 2606 OID 18155)
-- Name: fk_evento_patrocinador_patrocinador; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY evento_patrocinador
    ADD CONSTRAINT fk_evento_patrocinador_patrocinador FOREIGN KEY (patrocinador_id) REFERENCES patrocinador(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2235 (class 2606 OID 18160)
-- Name: fk_evento_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY evento
    ADD CONSTRAINT fk_evento_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2238 (class 2606 OID 18165)
-- Name: fk_localidad_localidad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY localidad
    ADD CONSTRAINT fk_localidad_localidad FOREIGN KEY (localidad_id) REFERENCES localidad(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2239 (class 2606 OID 18170)
-- Name: fk_pqrs_estado_pqrs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY pqrs
    ADD CONSTRAINT fk_pqrs_estado_pqrs FOREIGN KEY (estado_pqrs_id) REFERENCES estado_pqrs(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2240 (class 2606 OID 18175)
-- Name: fk_pqrs_tipo_pqrs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY pqrs
    ADD CONSTRAINT fk_pqrs_tipo_pqrs FOREIGN KEY (tipo_pqrs_id) REFERENCES tipo_pqrs(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2241 (class 2606 OID 18180)
-- Name: fk_pqrs_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY pqrs
    ADD CONSTRAINT fk_pqrs_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id);


--
-- TOC entry 2242 (class 2606 OID 18185)
-- Name: fk_recaudo_economico_evento; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY recaudo_economico
    ADD CONSTRAINT fk_recaudo_economico_evento FOREIGN KEY (evento_id) REFERENCES evento(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2243 (class 2606 OID 18190)
-- Name: fk_recaudo_economico_tarifa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY recaudo_economico
    ADD CONSTRAINT fk_recaudo_economico_tarifa FOREIGN KEY (tarifa_id) REFERENCES tarifa(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2244 (class 2606 OID 18195)
-- Name: fk_recaudo_economico_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY recaudo_economico
    ADD CONSTRAINT fk_recaudo_economico_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2245 (class 2606 OID 18200)
-- Name: fk_recordar_me_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY recordar_me
    ADD CONSTRAINT fk_recordar_me_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2246 (class 2606 OID 18205)
-- Name: fk_usuario_credencial_credencial; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_credencial_credencial FOREIGN KEY (credencial_id) REFERENCES credencial(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2247 (class 2606 OID 18210)
-- Name: fk_usuario_credencial_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_credencial_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2249 (class 2606 OID 18215)
-- Name: fk_usuario_gusta_categoria_categoria; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_gusta_categoria
    ADD CONSTRAINT fk_usuario_gusta_categoria_categoria FOREIGN KEY (categoria_id) REFERENCES categoria(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2250 (class 2606 OID 18220)
-- Name: fk_usuario_gusta_categoria_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_gusta_categoria
    ADD CONSTRAINT fk_usuario_gusta_categoria_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2248 (class 2606 OID 18225)
-- Name: fk_usuario_rol_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_rol_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2366 (class 0 OID 0)
-- Dependencies: 6
-- Name: public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO PUBLIC;


-- Completed on 2016-02-11 00:21:13 COT

--
-- PostgreSQL database dump complete
--

