--
-- PostgreSQL database dump
--

-- Dumped from database version 9.4.0
-- Dumped by pg_dump version 9.4.0
-- Started on 2015-04-30 23:46:54 COT

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

--
-- TOC entry 214 (class 3079 OID 11939)
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- TOC entry 2403 (class 0 OID 0)
-- Dependencies: 214
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET search_path = public, pg_catalog;

--
-- TOC entry 172 (class 1259 OID 17070)
-- Name: bitacora_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE bitacora_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2404 (class 0 OID 0)
-- Dependencies: 172
-- Name: SEQUENCE bitacora_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE bitacora_id_seq IS 'DbWrench Autogenerated Sequence.';


SET default_with_oids = false;

--
-- TOC entry 213 (class 1259 OID 19894)
-- Name: bitacora; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE bitacora (
    id bigint DEFAULT nextval('bitacora_id_seq'::regclass) NOT NULL,
    usuario_id bigint NOT NULL,
    accion character varying(80) NOT NULL,
    tabla character varying(80) NOT NULL,
    registro bigint,
    observacion character varying(1024),
    fecha timestamp without time zone DEFAULT now() NOT NULL
);


--
-- TOC entry 186 (class 1259 OID 17974)
-- Name: categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2405 (class 0 OID 0)
-- Dependencies: 186
-- Name: SEQUENCE categoria_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE categoria_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 198 (class 1259 OID 17998)
-- Name: categoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE categoria (
    id bigint DEFAULT nextval('categoria_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(45) NOT NULL
);


--
-- TOC entry 173 (class 1259 OID 17072)
-- Name: credencial_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE credencial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2406 (class 0 OID 0)
-- Dependencies: 173
-- Name: SEQUENCE credencial_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE credencial_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 177 (class 1259 OID 17092)
-- Name: credencial; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE credencial (
    id bigint DEFAULT nextval('credencial_id_seq'::regclass) NOT NULL,
    nombre character varying(80) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


--
-- TOC entry 187 (class 1259 OID 17976)
-- Name: dato_usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE dato_usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2407 (class 0 OID 0)
-- Dependencies: 187
-- Name: SEQUENCE dato_usuario_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE dato_usuario_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 199 (class 1259 OID 18006)
-- Name: dato_usuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE dato_usuario (
    id bigint DEFAULT nextval('dato_usuario_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    usuario_id bigint NOT NULL,
    nombre character varying(45) NOT NULL,
    apellido character varying(45) NOT NULL,
    correo character varying(70) NOT NULL,
    genero boolean NOT NULL,
    fecha_nacimiento date NOT NULL,
    localidad_id bigint NOT NULL,
    tipo_documento_id bigint NOT NULL,
    organizacion_id bigint
);


--
-- TOC entry 2408 (class 0 OID 0)
-- Dependencies: 199
-- Name: COLUMN dato_usuario.genero; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN dato_usuario.genero IS 'true = femenino | false = masculino';


--
-- TOC entry 181 (class 1259 OID 17964)
-- Name: detalle_pqrs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE detalle_pqrs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2409 (class 0 OID 0)
-- Dependencies: 181
-- Name: SEQUENCE detalle_pqrs_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE detalle_pqrs_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 200 (class 1259 OID 18018)
-- Name: detalle_pqrs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE detalle_pqrs (
    id bigint DEFAULT nextval('detalle_pqrs_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    pqrs_id bigint NOT NULL,
    respuesta character varying(2048) NOT NULL,
    usuario_id bigint NOT NULL
);


--
-- TOC entry 182 (class 1259 OID 17966)
-- Name: estado_pqrs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE estado_pqrs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2410 (class 0 OID 0)
-- Dependencies: 182
-- Name: SEQUENCE estado_pqrs_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE estado_pqrs_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 201 (class 1259 OID 18031)
-- Name: estado_pqrs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE estado_pqrs (
    id bigint DEFAULT nextval('estado_pqrs_id_seq'::regclass) NOT NULL,
    nombre character varying(50) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


--
-- TOC entry 2411 (class 0 OID 0)
-- Dependencies: 201
-- Name: COLUMN estado_pqrs.actived; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN estado_pqrs.actived IS 'TRUE activado ; FALSE desactivado';


--
-- TOC entry 188 (class 1259 OID 17978)
-- Name: evento_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE evento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2412 (class 0 OID 0)
-- Dependencies: 188
-- Name: SEQUENCE evento_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE evento_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 202 (class 1259 OID 18040)
-- Name: evento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE evento (
    id bigint DEFAULT nextval('evento_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    imagen character varying(37),
    nombre character varying(45) NOT NULL,
    descripcion character varying(1024) NOT NULL,
    fecha_inicial_evento timestamp without time zone NOT NULL,
    fecha_final_evento timestamp without time zone NOT NULL,
    lugar_latitud character varying(100) NOT NULL,
    lugar_longitud character varying(100) NOT NULL,
    direccion character varying(150) NOT NULL,
    costo integer DEFAULT 0,
    usuario_id bigint NOT NULL,
    categoria_id bigint,
    fecha_inicial_publicacion timestamp without time zone NOT NULL,
    fecha_final_publicacion timestamp without time zone NOT NULL
);


--
-- TOC entry 189 (class 1259 OID 17980)
-- Name: evento_patrocinador_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE evento_patrocinador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2413 (class 0 OID 0)
-- Dependencies: 189
-- Name: SEQUENCE evento_patrocinador_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE evento_patrocinador_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 203 (class 1259 OID 18054)
-- Name: evento_patrocinador; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE evento_patrocinador (
    id bigint DEFAULT nextval('evento_patrocinador_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    evento_id bigint NOT NULL,
    patrocinador_id bigint NOT NULL
);


--
-- TOC entry 190 (class 1259 OID 17982)
-- Name: localidad_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE localidad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2414 (class 0 OID 0)
-- Dependencies: 190
-- Name: SEQUENCE localidad_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE localidad_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 204 (class 1259 OID 18065)
-- Name: localidad; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE localidad (
    id bigint DEFAULT nextval('localidad_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(45) NOT NULL,
    localidad_id bigint
);


--
-- TOC entry 191 (class 1259 OID 17984)
-- Name: organizacion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE organizacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2415 (class 0 OID 0)
-- Dependencies: 191
-- Name: SEQUENCE organizacion_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE organizacion_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 205 (class 1259 OID 18074)
-- Name: organizacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE organizacion (
    id bigint DEFAULT nextval('organizacion_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(45) NOT NULL,
    direccion character varying(200) NOT NULL,
    telefono character varying(45) NOT NULL,
    fax character varying(45),
    correo character varying(100) NOT NULL,
    pagina_web character varying(100)
);


--
-- TOC entry 192 (class 1259 OID 17986)
-- Name: patrocinador_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE patrocinador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2416 (class 0 OID 0)
-- Dependencies: 192
-- Name: SEQUENCE patrocinador_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE patrocinador_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 206 (class 1259 OID 18085)
-- Name: patrocinador; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE patrocinador (
    id bigint DEFAULT nextval('patrocinador_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(45) NOT NULL,
    telefono character varying(10),
    correo character varying(150) NOT NULL,
    direccion character varying(150)
);


--
-- TOC entry 183 (class 1259 OID 17968)
-- Name: pqrs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE pqrs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2417 (class 0 OID 0)
-- Dependencies: 183
-- Name: SEQUENCE pqrs_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE pqrs_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 207 (class 1259 OID 18093)
-- Name: pqrs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE pqrs (
    id bigint DEFAULT nextval('pqrs_id_seq'::regclass) NOT NULL,
    tipo_pqrs_id bigint NOT NULL,
    estado_pqrs_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    titulo character varying(50) NOT NULL,
    contenido character varying(2048) NOT NULL,
    usuario_id bigint NOT NULL
);


--
-- TOC entry 193 (class 1259 OID 17988)
-- Name: recaudo_economico_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE recaudo_economico_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2418 (class 0 OID 0)
-- Dependencies: 193
-- Name: SEQUENCE recaudo_economico_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE recaudo_economico_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 208 (class 1259 OID 18106)
-- Name: recaudo_economico; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE recaudo_economico (
    id bigint DEFAULT nextval('recaudo_economico_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    evento_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    observacion character varying(1024),
    tarifa_id bigint NOT NULL,
    valor_total bigint DEFAULT 0 NOT NULL,
    valor_parcial bigint DEFAULT 0 NOT NULL
);


--
-- TOC entry 174 (class 1259 OID 17074)
-- Name: recordar_me_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE recordar_me_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2419 (class 0 OID 0)
-- Dependencies: 174
-- Name: SEQUENCE recordar_me_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE recordar_me_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 178 (class 1259 OID 17100)
-- Name: recordar_me; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE recordar_me (
    id bigint DEFAULT nextval('recordar_me_id_seq'::regclass) NOT NULL,
    usuario_id bigint NOT NULL,
    ip_address character varying(50) NOT NULL,
    hash_cookie character varying(32) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- TOC entry 194 (class 1259 OID 17990)
-- Name: rol_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2420 (class 0 OID 0)
-- Dependencies: 194
-- Name: SEQUENCE rol_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE rol_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 184 (class 1259 OID 17970)
-- Name: tarifa_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE tarifa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2421 (class 0 OID 0)
-- Dependencies: 184
-- Name: SEQUENCE tarifa_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE tarifa_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 209 (class 1259 OID 18122)
-- Name: tarifa; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE tarifa (
    id bigint DEFAULT nextval('tarifa_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    descripcion character varying(1024) NOT NULL,
    valor bigint NOT NULL,
    actived boolean DEFAULT true NOT NULL
);


--
-- TOC entry 2422 (class 0 OID 0)
-- Dependencies: 209
-- Name: COLUMN tarifa.actived; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN tarifa.actived IS 'TRUE activado ; FALSE desactivado';


--
-- TOC entry 195 (class 1259 OID 17992)
-- Name: tipo_documento_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE tipo_documento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2423 (class 0 OID 0)
-- Dependencies: 195
-- Name: SEQUENCE tipo_documento_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE tipo_documento_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 210 (class 1259 OID 18134)
-- Name: tipo_documento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE tipo_documento (
    id bigint DEFAULT nextval('tipo_documento_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(45) NOT NULL
);


--
-- TOC entry 185 (class 1259 OID 17972)
-- Name: tipo_pqrs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE tipo_pqrs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2424 (class 0 OID 0)
-- Dependencies: 185
-- Name: SEQUENCE tipo_pqrs_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE tipo_pqrs_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 211 (class 1259 OID 18142)
-- Name: tipo_pqrs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE tipo_pqrs (
    id bigint DEFAULT nextval('tipo_pqrs_id_seq'::regclass) NOT NULL,
    nombre character varying(50) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


--
-- TOC entry 2425 (class 0 OID 0)
-- Dependencies: 211
-- Name: COLUMN tipo_pqrs.actived; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN tipo_pqrs.actived IS 'TRUE activado ; FALSE desactivado';


--
-- TOC entry 175 (class 1259 OID 17076)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2426 (class 0 OID 0)
-- Dependencies: 175
-- Name: SEQUENCE usuario_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE usuario_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 179 (class 1259 OID 17109)
-- Name: usuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE usuario (
    id bigint DEFAULT nextval('usuario_id_seq'::regclass) NOT NULL,
    user_name character varying(80) NOT NULL,
    password character varying(32) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    last_login_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


--
-- TOC entry 2427 (class 0 OID 0)
-- Dependencies: 179
-- Name: COLUMN usuario.actived; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN usuario.actived IS 'TRUE = activado | FALSE = desactivado';


--
-- TOC entry 176 (class 1259 OID 17078)
-- Name: usuario_credencial_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE usuario_credencial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2428 (class 0 OID 0)
-- Dependencies: 176
-- Name: SEQUENCE usuario_credencial_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE usuario_credencial_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 180 (class 1259 OID 17122)
-- Name: usuario_credencial; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE usuario_credencial (
    id bigint DEFAULT nextval('usuario_credencial_id_seq'::regclass) NOT NULL,
    usuario_id bigint NOT NULL,
    credencial_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- TOC entry 196 (class 1259 OID 17994)
-- Name: usuario_gusta_categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE usuario_gusta_categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2429 (class 0 OID 0)
-- Dependencies: 196
-- Name: SEQUENCE usuario_gusta_categoria_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE usuario_gusta_categoria_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 212 (class 1259 OID 18151)
-- Name: usuario_gusta_categoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE usuario_gusta_categoria (
    id bigint DEFAULT nextval('usuario_gusta_categoria_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    usuario_id bigint NOT NULL,
    categoria_id bigint NOT NULL
);


--
-- TOC entry 197 (class 1259 OID 17996)
-- Name: usuario_rol_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE usuario_rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2430 (class 0 OID 0)
-- Dependencies: 197
-- Name: SEQUENCE usuario_rol_id_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE usuario_rol_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 2397 (class 0 OID 19894)
-- Dependencies: 213
-- Data for Name: bitacora; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (1, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-03-02 15:15:06');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (2, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-03-02 15:15:11');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (3, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-03-02 15:39:32');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (4, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-03-02 15:39:50');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (5, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-03-06 18:50:14');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (6, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-03-06 19:30:18');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (7, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-03-08 13:19:42');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (8, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-03-08 13:20:53');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (9, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-03-08 13:21:32');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (10, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-03-08 13:24:55');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (11, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-03-08 13:28:58');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (12, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-05 22:53:47');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (13, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-04-05 22:54:00');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (14, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-17 18:52:30');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (15, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-27 10:08:20');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (16, 1, 'salida del sistema', 'NINGUNA', NULL, NULL, '2015-04-27 10:18:02');


--
-- TOC entry 2431 (class 0 OID 0)
-- Dependencies: 172
-- Name: bitacora_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('bitacora_id_seq', 16, true);


--
-- TOC entry 2382 (class 0 OID 17998)
-- Dependencies: 198
-- Data for Name: categoria; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 2432 (class 0 OID 0)
-- Dependencies: 186
-- Name: categoria_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('categoria_id_seq', 1, false);


--
-- TOC entry 2361 (class 0 OID 17092)
-- Dependencies: 177
-- Data for Name: credencial; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO credencial (id, nombre, created_at, updated_at, deleted_at) VALUES (1, 'admin', '2015-03-02 14:57:29.961464', '2015-03-02 14:57:29.961464', NULL);
INSERT INTO credencial (id, nombre, created_at, updated_at, deleted_at) VALUES (2, 'usuario', '2015-03-02 14:57:29.961464', '2015-03-02 14:57:29.961464', NULL);


--
-- TOC entry 2433 (class 0 OID 0)
-- Dependencies: 173
-- Name: credencial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('credencial_id_seq', 2, true);


--
-- TOC entry 2383 (class 0 OID 18006)
-- Dependencies: 199
-- Data for Name: dato_usuario; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 2434 (class 0 OID 0)
-- Dependencies: 187
-- Name: dato_usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('dato_usuario_id_seq', 1, false);


--
-- TOC entry 2384 (class 0 OID 18018)
-- Dependencies: 200
-- Data for Name: detalle_pqrs; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 2435 (class 0 OID 0)
-- Dependencies: 181
-- Name: detalle_pqrs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('detalle_pqrs_id_seq', 1, false);


--
-- TOC entry 2385 (class 0 OID 18031)
-- Dependencies: 201
-- Data for Name: estado_pqrs; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 2436 (class 0 OID 0)
-- Dependencies: 182
-- Name: estado_pqrs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('estado_pqrs_id_seq', 1, false);


--
-- TOC entry 2386 (class 0 OID 18040)
-- Dependencies: 202
-- Data for Name: evento; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 2437 (class 0 OID 0)
-- Dependencies: 188
-- Name: evento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('evento_id_seq', 1, false);


--
-- TOC entry 2387 (class 0 OID 18054)
-- Dependencies: 203
-- Data for Name: evento_patrocinador; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 2438 (class 0 OID 0)
-- Dependencies: 189
-- Name: evento_patrocinador_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('evento_patrocinador_id_seq', 1, false);


--
-- TOC entry 2388 (class 0 OID 18065)
-- Dependencies: 204
-- Data for Name: localidad; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 2439 (class 0 OID 0)
-- Dependencies: 190
-- Name: localidad_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('localidad_id_seq', 1, false);


--
-- TOC entry 2389 (class 0 OID 18074)
-- Dependencies: 205
-- Data for Name: organizacion; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 2440 (class 0 OID 0)
-- Dependencies: 191
-- Name: organizacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('organizacion_id_seq', 1, false);


--
-- TOC entry 2390 (class 0 OID 18085)
-- Dependencies: 206
-- Data for Name: patrocinador; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 2441 (class 0 OID 0)
-- Dependencies: 192
-- Name: patrocinador_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('patrocinador_id_seq', 1, false);


--
-- TOC entry 2391 (class 0 OID 18093)
-- Dependencies: 207
-- Data for Name: pqrs; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 2442 (class 0 OID 0)
-- Dependencies: 183
-- Name: pqrs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('pqrs_id_seq', 1, false);


--
-- TOC entry 2392 (class 0 OID 18106)
-- Dependencies: 208
-- Data for Name: recaudo_economico; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 2443 (class 0 OID 0)
-- Dependencies: 193
-- Name: recaudo_economico_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('recaudo_economico_id_seq', 1, false);


--
-- TOC entry 2362 (class 0 OID 17100)
-- Dependencies: 178
-- Data for Name: recordar_me; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 2444 (class 0 OID 0)
-- Dependencies: 174
-- Name: recordar_me_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('recordar_me_id_seq', 1, false);


--
-- TOC entry 2445 (class 0 OID 0)
-- Dependencies: 194
-- Name: rol_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('rol_id_seq', 1, false);


--
-- TOC entry 2393 (class 0 OID 18122)
-- Dependencies: 209
-- Data for Name: tarifa; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 2446 (class 0 OID 0)
-- Dependencies: 184
-- Name: tarifa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('tarifa_id_seq', 1, false);


--
-- TOC entry 2394 (class 0 OID 18134)
-- Dependencies: 210
-- Data for Name: tipo_documento; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 2447 (class 0 OID 0)
-- Dependencies: 195
-- Name: tipo_documento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('tipo_documento_id_seq', 1, false);


--
-- TOC entry 2395 (class 0 OID 18142)
-- Dependencies: 211
-- Data for Name: tipo_pqrs; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 2448 (class 0 OID 0)
-- Dependencies: 185
-- Name: tipo_pqrs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('tipo_pqrs_id_seq', 1, false);


--
-- TOC entry 2363 (class 0 OID 17109)
-- Dependencies: 179
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (78, 'lorena', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-24 21:45:10.127404', '2015-04-24 21:45:10.127404', '2015-04-25 23:17:37');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (92, 'ramon', 'asdf', true, NULL, '2015-04-27 00:41:46.508649', '2015-04-27 00:41:46.508649', '2015-04-27 00:55:55');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (47, 'laloi', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-06 12:48:37.643141', '2015-04-06 12:48:37.643141', '2015-04-27 00:56:50');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (72, 'loalslsk', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-22 13:45:54.343195', '2015-04-22 13:45:54.343195', '2015-04-27 00:56:50');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (2, 'admin2', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-03-28 13:27:53.91044', '2015-03-28 13:27:53.91044', '2015-03-28 13:28:00');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (93, 'lulosawa', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-27 00:42:53.406771', '2015-04-27 00:42:53.406771', '2015-04-27 00:56:50');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (41, 'koko', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-06 11:16:00.5476', '2015-04-06 11:16:00.5476', '2015-04-27 00:57:34');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (54, 'khubo', '5d98ec0427152056397e9e35f357be87', true, NULL, '2015-04-20 12:25:46.544613', '2015-04-20 12:25:46.544613', '2015-04-27 00:59:03');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (94, 'kawasaki', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-27 00:43:20.794773', '2015-04-27 00:43:20.794773', '2015-04-27 00:59:27');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (43, 'kakekikoku', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-06 12:41:43.192067', '2015-04-06 12:41:43.192067', '2015-04-27 01:00:59');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (81, 'julio', 'a', true, NULL, '2015-04-24 23:42:00.870208', '2015-04-24 23:42:00.870208', '2015-04-27 02:19:58');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (82, 'julian', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-24 23:42:11.795644', '2015-04-24 23:42:11.795644', '2015-04-27 03:46:18');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (1, 'admin', '202cb962ac59075b964b07152d234b70', true, '2015-04-27 10:08:20', '2015-03-02 14:57:29.961464', '2015-03-02 14:57:29.961464', NULL);
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (48, 'admin490', '123', true, NULL, '2015-04-08 08:20:32.705172', '2015-04-08 08:20:32.705172', '2015-04-21 18:22:06');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (38, 'admin098789lol', '', true, NULL, '2015-04-06 00:36:51.035453', '2015-04-06 00:36:51.035453', '2015-04-21 18:22:28');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (40, 'adminholasiu', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-06 00:41:49.1144', '2015-04-06 00:41:49.1144', '2015-04-21 18:22:28');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (97, 'waloskd', '123', true, NULL, '2015-04-27 10:22:15.615393', '2015-04-27 10:22:15.615393', '2015-04-27 11:08:33');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (49, 'jorge', '123', true, NULL, '2015-04-08 08:38:21.365033', '2015-04-08 08:38:21.365033', '2015-04-27 11:08:43');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (87, 'holmes', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-25 23:08:49.765043', '2015-04-25 23:08:49.765043', '2015-04-27 11:08:55');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (99, 'jalf', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-27 11:07:58.433241', '2015-04-27 11:07:58.433241', '2015-04-27 11:08:55');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (46, 'admon', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-06 12:48:22.032013', '2015-04-06 12:48:22.032013', '2015-04-22 10:47:59');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (58, 'admonisc', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-20 18:47:22.264298', '2015-04-20 18:47:22.264298', '2015-04-22 10:48:16');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (56, 'adminaso343', '111', true, NULL, '2015-04-20 12:31:11.224525', '2015-04-20 12:31:11.224525', '2015-04-22 10:48:35');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (19, 'admin6', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-03-28 14:58:20.401068', '2015-03-28 14:58:20.401068', '2015-03-28 15:55:25');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (57, 'admonistr', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-20 18:40:46.769443', '2015-04-20 18:40:46.769443', '2015-04-22 10:48:35');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (55, 'admsond', '5d98ec0427152056397e9e35f357be87', true, NULL, '2015-04-20 12:26:22.243943', '2015-04-20 12:26:22.243943', '2015-04-22 10:58:03');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (70, 'adsofosllso', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-22 10:45:06.075729', '2015-04-22 10:45:06.075729', '2015-04-22 10:58:17');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (35, 'holaMundo', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-05 14:21:43.131603', '2015-04-05 14:21:43.131603', '2015-04-05 14:57:07');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (42, 'trololoo', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-06 11:16:10.049162', '2015-04-06 11:16:10.049162', '2015-04-22 13:46:21');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (21, 'admin10', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-03-30 20:52:37.654035', '2015-03-30 20:52:37.654035', '2015-03-30 20:52:54');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (59, 'adslslsl', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-21 16:26:37.005187', '2015-04-21 16:26:37.005187', '2015-04-24 02:57:35');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (71, 'adsosl', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-22 13:08:00.734709', '2015-04-22 13:08:00.734709', '2015-04-24 02:57:45');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (24, 'admin8', 'd41d8cd98f00b204e9800998ecf8427e', true, NULL, '2015-04-01 17:14:09.210188', '2015-04-01 17:14:09.210188', '2015-04-01 17:14:19');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (22, 'admin123', '', true, NULL, '2015-04-01 16:43:37.883155', '2015-04-01 16:43:37.883155', '2015-04-04 22:08:38');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (27, '54321', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-04 22:18:59.911526', '2015-04-04 22:18:59.911526', '2015-04-04 22:19:34');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (26, 'ad123', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-04 22:18:49.623822', '2015-04-04 22:18:49.623822', '2015-04-04 22:19:34');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (25, 'admin3453', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-04 22:13:48.680009', '2015-04-04 22:13:48.680009', '2015-04-04 22:19:34');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (79, 'james', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-24 21:45:24.435463', '2015-04-24 21:45:24.435463', NULL);
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (28, '', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-04 23:22:15.301504', '2015-04-04 23:22:15.301504', '2015-04-04 23:22:33');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (76, 'zinuco', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-24 20:39:26.88208', '2015-04-24 20:39:26.88208', '2015-04-24 23:45:03');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (45, 'trololo', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-06 12:44:20.109145', '2015-04-06 12:44:20.109145', '2015-04-25 20:47:55');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (33, '458adminsql', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-05 00:05:22.592973', '2015-04-05 00:05:22.592973', '2015-04-05 14:57:58');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (75, 'albertoto', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-24 20:39:07.860721', '2015-04-24 20:39:07.860721', '2015-04-25 21:13:48');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (65, 'armando', 'd41d8cd98f00b204e9800998ecf8427e', true, NULL, '2015-04-22 10:17:06.006533', '2015-04-22 10:17:06.006533', '2015-04-25 21:22:00');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (37, 'add', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-05 14:58:39.163382', '2015-04-05 14:58:39.163382', '2015-04-05 14:58:49');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (36, 'xqsl', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-05 14:58:14.518064', '2015-04-05 14:58:14.518064', '2015-04-05 14:58:49');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (77, 'rodrigo', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-24 20:44:49.919755', '2015-04-24 20:44:49.919755', '2015-04-25 21:22:39');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (83, 'Alveiro', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-24 23:42:22.831769', '2015-04-24 23:42:22.831769', '2015-04-25 21:24:16');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (84, 'fabregas', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-25 21:25:45.359004', '2015-04-25 21:25:45.359004', NULL);
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (85, 'cesc', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-25 21:26:01.06933', '2015-04-25 21:26:01.06933', '2015-04-25 21:43:41');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (86, 'alonso', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-25 21:26:14.253533', '2015-04-25 21:26:14.253533', '2015-04-25 23:04:48');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (80, 'cristiano', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-24 21:45:41.807482', '2015-04-24 21:45:41.807482', '2015-04-25 23:04:49');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (44, 'mamemimo', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-06 12:43:43.049165', '2015-04-06 12:43:43.049165', '2015-04-25 23:05:13');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (89, 'neron', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-25 23:09:18.325068', '2015-04-25 23:09:18.325068', '2015-04-25 23:10:03');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (90, 'rocky', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-25 23:09:30.976503', '2015-04-25 23:09:30.976503', '2015-04-25 23:10:03');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (88, 'lukas', '202cb962ac59075b964b07152d234b70', true, NULL, '2015-04-25 23:09:05.788623', '2015-04-25 23:09:05.788623', '2015-04-25 23:10:17');
INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (91, 'cangrejos', '123', true, NULL, '2015-04-25 23:09:41.98701', '2015-04-25 23:09:41.98701', NULL);


--
-- TOC entry 2364 (class 0 OID 17122)
-- Dependencies: 180
-- Data for Name: usuario_credencial; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO usuario_credencial (id, usuario_id, credencial_id, created_at) VALUES (1, 1, 1, '2015-03-02 14:57:29.961464');


--
-- TOC entry 2449 (class 0 OID 0)
-- Dependencies: 176
-- Name: usuario_credencial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('usuario_credencial_id_seq', 1, true);


--
-- TOC entry 2396 (class 0 OID 18151)
-- Dependencies: 212
-- Data for Name: usuario_gusta_categoria; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 2450 (class 0 OID 0)
-- Dependencies: 196
-- Name: usuario_gusta_categoria_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('usuario_gusta_categoria_id_seq', 1, false);


--
-- TOC entry 2451 (class 0 OID 0)
-- Dependencies: 175
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('usuario_id_seq', 99, true);


--
-- TOC entry 2452 (class 0 OID 0)
-- Dependencies: 197
-- Name: usuario_rol_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('usuario_rol_id_seq', 1, false);


--
-- TOC entry 2222 (class 2606 OID 19903)
-- Name: pkbitacora; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY bitacora
    ADD CONSTRAINT pkbitacora PRIMARY KEY (id);


--
-- TOC entry 2170 (class 2606 OID 18005)
-- Name: pkcategoria; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY categoria
    ADD CONSTRAINT pkcategoria PRIMARY KEY (id);


--
-- TOC entry 2153 (class 2606 OID 17099)
-- Name: pkcredencial; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY credencial
    ADD CONSTRAINT pkcredencial PRIMARY KEY (id);


--
-- TOC entry 2176 (class 2606 OID 18013)
-- Name: pkdato_usuario; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY dato_usuario
    ADD CONSTRAINT pkdato_usuario PRIMARY KEY (id);


--
-- TOC entry 2180 (class 2606 OID 18028)
-- Name: pkdetalle_pqrs; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY detalle_pqrs
    ADD CONSTRAINT pkdetalle_pqrs PRIMARY KEY (id);


--
-- TOC entry 2182 (class 2606 OID 18039)
-- Name: pkestado_pqrs; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY estado_pqrs
    ADD CONSTRAINT pkestado_pqrs PRIMARY KEY (id);


--
-- TOC entry 2186 (class 2606 OID 18051)
-- Name: pkevento; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY evento
    ADD CONSTRAINT pkevento PRIMARY KEY (id);


--
-- TOC entry 2191 (class 2606 OID 18061)
-- Name: pkevento_patrocinador; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY evento_patrocinador
    ADD CONSTRAINT pkevento_patrocinador PRIMARY KEY (id);


--
-- TOC entry 2194 (class 2606 OID 18072)
-- Name: pklocalidad; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY localidad
    ADD CONSTRAINT pklocalidad PRIMARY KEY (id);


--
-- TOC entry 2196 (class 2606 OID 18084)
-- Name: pkorganizacion; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY organizacion
    ADD CONSTRAINT pkorganizacion PRIMARY KEY (id);


--
-- TOC entry 2198 (class 2606 OID 18092)
-- Name: pkpatrocinador; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY patrocinador
    ADD CONSTRAINT pkpatrocinador PRIMARY KEY (id);


--
-- TOC entry 2200 (class 2606 OID 18103)
-- Name: pkpqrs; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY pqrs
    ADD CONSTRAINT pkpqrs PRIMARY KEY (id);


--
-- TOC entry 2204 (class 2606 OID 18118)
-- Name: pkrecaudo_economico; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY recaudo_economico
    ADD CONSTRAINT pkrecaudo_economico PRIMARY KEY (id);


--
-- TOC entry 2155 (class 2606 OID 17106)
-- Name: pkrecordar_me; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY recordar_me
    ADD CONSTRAINT pkrecordar_me PRIMARY KEY (id);


--
-- TOC entry 2209 (class 2606 OID 18133)
-- Name: pktarifa; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY tarifa
    ADD CONSTRAINT pktarifa PRIMARY KEY (id);


--
-- TOC entry 2211 (class 2606 OID 18141)
-- Name: pktipo_documento; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY tipo_documento
    ADD CONSTRAINT pktipo_documento PRIMARY KEY (id);


--
-- TOC entry 2213 (class 2606 OID 18150)
-- Name: pktipo_pqrs; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY tipo_pqrs
    ADD CONSTRAINT pktipo_pqrs PRIMARY KEY (id);


--
-- TOC entry 2159 (class 2606 OID 17117)
-- Name: pkusuario; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY usuario
    ADD CONSTRAINT pkusuario PRIMARY KEY (id);


--
-- TOC entry 2165 (class 2606 OID 17128)
-- Name: pkusuario_credencial; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT pkusuario_credencial PRIMARY KEY (id);


--
-- TOC entry 2215 (class 2606 OID 18158)
-- Name: pkusuario_gusta_categoria; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY usuario_gusta_categoria
    ADD CONSTRAINT pkusuario_gusta_categoria PRIMARY KEY (id);


--
-- TOC entry 2219 (class 1259 OID 19904)
-- Name: bitacora_fecha_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "bitacora_fecha_Idx" ON bitacora USING btree (fecha);


--
-- TOC entry 2220 (class 1259 OID 19905)
-- Name: bitacora_usuario_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "bitacora_usuario_id_Idx" ON bitacora USING btree (usuario_id);


--
-- TOC entry 2171 (class 1259 OID 18014)
-- Name: dato_usuario_localidad_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "dato_usuario_localidad_id_Idx" ON dato_usuario USING btree (localidad_id);


--
-- TOC entry 2172 (class 1259 OID 18015)
-- Name: dato_usuario_organizacion_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "dato_usuario_organizacion_id_Idx" ON dato_usuario USING btree (organizacion_id);


--
-- TOC entry 2173 (class 1259 OID 18016)
-- Name: dato_usuario_tipo_documento_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "dato_usuario_tipo_documento_id_Idx" ON dato_usuario USING btree (tipo_documento_id);


--
-- TOC entry 2174 (class 1259 OID 18017)
-- Name: dato_usuario_usuario_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "dato_usuario_usuario_id_Idx" ON dato_usuario USING btree (usuario_id);


--
-- TOC entry 2177 (class 1259 OID 18029)
-- Name: detalle_pqrs_pqrs_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "detalle_pqrs_pqrs_id_Idx" ON detalle_pqrs USING btree (pqrs_id);


--
-- TOC entry 2178 (class 1259 OID 18030)
-- Name: detalle_pqrs_usuario_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "detalle_pqrs_usuario_id_Idx" ON detalle_pqrs USING btree (usuario_id);


--
-- TOC entry 2183 (class 1259 OID 18052)
-- Name: evento_categoria_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "evento_categoria_id_Idx" ON evento USING btree (categoria_id);


--
-- TOC entry 2187 (class 1259 OID 18062)
-- Name: evento_patrocinador_evento_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "evento_patrocinador_evento_id_Idx" ON evento_patrocinador USING btree (evento_id);


--
-- TOC entry 2188 (class 1259 OID 18063)
-- Name: evento_patrocinador_evento_id_patrocinador_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "evento_patrocinador_evento_id_patrocinador_id_Idx" ON evento_patrocinador USING btree (evento_id, patrocinador_id);


--
-- TOC entry 2189 (class 1259 OID 18064)
-- Name: evento_patrocinador_patrocinador_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "evento_patrocinador_patrocinador_id_Idx" ON evento_patrocinador USING btree (patrocinador_id);


--
-- TOC entry 2184 (class 1259 OID 18053)
-- Name: evento_usuario_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "evento_usuario_id_Idx" ON evento USING btree (usuario_id);


--
-- TOC entry 2192 (class 1259 OID 18073)
-- Name: localidad_localidad_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "localidad_localidad_id_Idx" ON localidad USING btree (localidad_id);


--
-- TOC entry 2201 (class 1259 OID 18104)
-- Name: pqrs_tipo_pqrs_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "pqrs_tipo_pqrs_id_Idx" ON pqrs USING btree (tipo_pqrs_id);


--
-- TOC entry 2202 (class 1259 OID 18105)
-- Name: pqrs_usuario_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "pqrs_usuario_id_Idx" ON pqrs USING btree (usuario_id);


--
-- TOC entry 2205 (class 1259 OID 18119)
-- Name: recaudo_economico_evento_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "recaudo_economico_evento_id_Idx" ON recaudo_economico USING btree (evento_id);


--
-- TOC entry 2206 (class 1259 OID 18120)
-- Name: recaudo_economico_tarifa_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "recaudo_economico_tarifa_id_Idx" ON recaudo_economico USING btree (tarifa_id);


--
-- TOC entry 2207 (class 1259 OID 18121)
-- Name: recaudo_economico_usuario_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "recaudo_economico_usuario_id_Idx" ON recaudo_economico USING btree (usuario_id);


--
-- TOC entry 2156 (class 1259 OID 17107)
-- Name: recordar_me_ip_address_hash_cookie_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "recordar_me_ip_address_hash_cookie_Idx" ON recordar_me USING btree (ip_address, hash_cookie);


--
-- TOC entry 2157 (class 1259 OID 17108)
-- Name: recordar_me_usuario_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "recordar_me_usuario_id_Idx" ON recordar_me USING btree (usuario_id);


--
-- TOC entry 2160 (class 1259 OID 17118)
-- Name: usuario_actived_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "usuario_actived_Idx" ON usuario USING btree (actived);


--
-- TOC entry 2166 (class 1259 OID 17129)
-- Name: usuario_credencial_credencial_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "usuario_credencial_credencial_id_Idx" ON usuario_credencial USING btree (credencial_id);


--
-- TOC entry 2167 (class 1259 OID 17130)
-- Name: usuario_credencial_usuario_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "usuario_credencial_usuario_id_Idx" ON usuario_credencial USING btree (usuario_id);


--
-- TOC entry 2168 (class 1259 OID 17131)
-- Name: usuario_credencial_usuario_id_credencial_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "usuario_credencial_usuario_id_credencial_id_Idx" ON usuario_credencial USING btree (usuario_id, credencial_id);


--
-- TOC entry 2161 (class 1259 OID 17119)
-- Name: usuario_deleted_at_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "usuario_deleted_at_Idx" ON usuario USING btree (deleted_at);


--
-- TOC entry 2216 (class 1259 OID 18159)
-- Name: usuario_gusta_categoria_categoria_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "usuario_gusta_categoria_categoria_id_Idx" ON usuario_gusta_categoria USING btree (categoria_id);


--
-- TOC entry 2217 (class 1259 OID 18160)
-- Name: usuario_gusta_categoria_usuario_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "usuario_gusta_categoria_usuario_id_Idx" ON usuario_gusta_categoria USING btree (usuario_id);


--
-- TOC entry 2218 (class 1259 OID 18161)
-- Name: usuario_gusta_categoria_usuario_id_categoria_id_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "usuario_gusta_categoria_usuario_id_categoria_id_Idx" ON usuario_gusta_categoria USING btree (usuario_id, categoria_id);


--
-- TOC entry 2162 (class 1259 OID 17120)
-- Name: usuario_user_name_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "usuario_user_name_Idx" ON usuario USING btree (user_name);


--
-- TOC entry 2163 (class 1259 OID 17121)
-- Name: usuario_user_name_password_Idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "usuario_user_name_password_Idx" ON usuario USING btree (user_name, password);


--
-- TOC entry 2246 (class 2606 OID 19906)
-- Name: fk_bitacora_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY bitacora
    ADD CONSTRAINT fk_bitacora_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2227 (class 2606 OID 18162)
-- Name: fk_dato_usuario_localidad; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY dato_usuario
    ADD CONSTRAINT fk_dato_usuario_localidad FOREIGN KEY (localidad_id) REFERENCES localidad(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2228 (class 2606 OID 18167)
-- Name: fk_dato_usuario_organizacion; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY dato_usuario
    ADD CONSTRAINT fk_dato_usuario_organizacion FOREIGN KEY (organizacion_id) REFERENCES organizacion(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2229 (class 2606 OID 18172)
-- Name: fk_dato_usuario_tipo_documento; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY dato_usuario
    ADD CONSTRAINT fk_dato_usuario_tipo_documento FOREIGN KEY (tipo_documento_id) REFERENCES tipo_documento(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2230 (class 2606 OID 18177)
-- Name: fk_dato_usuario_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY dato_usuario
    ADD CONSTRAINT fk_dato_usuario_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2231 (class 2606 OID 18182)
-- Name: fk_detalle_pqrs_pqrs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY detalle_pqrs
    ADD CONSTRAINT fk_detalle_pqrs_pqrs FOREIGN KEY (pqrs_id) REFERENCES pqrs(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2232 (class 2606 OID 18187)
-- Name: fk_detalle_pqrs_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY detalle_pqrs
    ADD CONSTRAINT fk_detalle_pqrs_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2233 (class 2606 OID 18192)
-- Name: fk_evento_categoria; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY evento
    ADD CONSTRAINT fk_evento_categoria FOREIGN KEY (categoria_id) REFERENCES categoria(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2235 (class 2606 OID 18202)
-- Name: fk_evento_patrocinador_evento; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY evento_patrocinador
    ADD CONSTRAINT fk_evento_patrocinador_evento FOREIGN KEY (evento_id) REFERENCES evento(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2236 (class 2606 OID 18207)
-- Name: fk_evento_patrocinador_patrocinador; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY evento_patrocinador
    ADD CONSTRAINT fk_evento_patrocinador_patrocinador FOREIGN KEY (patrocinador_id) REFERENCES patrocinador(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2234 (class 2606 OID 18197)
-- Name: fk_evento_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY evento
    ADD CONSTRAINT fk_evento_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2237 (class 2606 OID 18212)
-- Name: fk_localidad_localidad; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY localidad
    ADD CONSTRAINT fk_localidad_localidad FOREIGN KEY (localidad_id) REFERENCES localidad(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2238 (class 2606 OID 18217)
-- Name: fk_pqrs_estado_pqrs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY pqrs
    ADD CONSTRAINT fk_pqrs_estado_pqrs FOREIGN KEY (estado_pqrs_id) REFERENCES estado_pqrs(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2239 (class 2606 OID 18222)
-- Name: fk_pqrs_tipo_pqrs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY pqrs
    ADD CONSTRAINT fk_pqrs_tipo_pqrs FOREIGN KEY (tipo_pqrs_id) REFERENCES tipo_pqrs(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2240 (class 2606 OID 18227)
-- Name: fk_pqrs_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY pqrs
    ADD CONSTRAINT fk_pqrs_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id);


--
-- TOC entry 2241 (class 2606 OID 18232)
-- Name: fk_recaudo_economico_evento; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY recaudo_economico
    ADD CONSTRAINT fk_recaudo_economico_evento FOREIGN KEY (evento_id) REFERENCES evento(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2242 (class 2606 OID 18237)
-- Name: fk_recaudo_economico_tarifa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY recaudo_economico
    ADD CONSTRAINT fk_recaudo_economico_tarifa FOREIGN KEY (tarifa_id) REFERENCES tarifa(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2243 (class 2606 OID 18242)
-- Name: fk_recaudo_economico_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY recaudo_economico
    ADD CONSTRAINT fk_recaudo_economico_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2223 (class 2606 OID 17137)
-- Name: fk_recordar_me_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY recordar_me
    ADD CONSTRAINT fk_recordar_me_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2224 (class 2606 OID 17142)
-- Name: fk_usuario_credencial_credencial; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_credencial_credencial FOREIGN KEY (credencial_id) REFERENCES credencial(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2225 (class 2606 OID 17147)
-- Name: fk_usuario_credencial_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_credencial_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2244 (class 2606 OID 18252)
-- Name: fk_usuario_gusta_categoria_categoria; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY usuario_gusta_categoria
    ADD CONSTRAINT fk_usuario_gusta_categoria_categoria FOREIGN KEY (categoria_id) REFERENCES categoria(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2245 (class 2606 OID 18257)
-- Name: fk_usuario_gusta_categoria_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY usuario_gusta_categoria
    ADD CONSTRAINT fk_usuario_gusta_categoria_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2226 (class 2606 OID 18247)
-- Name: fk_usuario_rol_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_rol_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


-- Completed on 2015-04-30 23:46:57 COT

--
-- PostgreSQL database dump complete
--

